name: this is my first job
on: workflow_dispatch
jobs: 
    first_job:
       runs-on: ubuntu-latest
       steps:
          - name: Print hello
            run: echo  "Hello World"
          - name: print goodbye
            run: echo "GOODbye"
          - name: Set up Node.js 16.14.0
            uses: actions/setup-node@v3
            with:
             node-version: '16.14.0'
          - name: Check Node.js version
            run: node --version
